### ISSUE TITLE
Warning message breaks drush.

### ISSUE THREAD

**Issue by jacobSingh** [greggles/vulnerable#1]
drush @dev7 en -y devel
This site is running the "Vulnerable" module which should never be enabled on a public website.  If this is a public website, you should probably disabling it          [error]
[jacob@jacob-mbp vulnerable]$

**Comment by greggles** [comment]
Should we check if it's in CLI mode and not print the message? Is there some other means that is more appropriate?

I agree this is annoying.

**Comment by greggles** [comment]
Fixed with your pull request - thanks!
